apiVersion: apps/v1
kind: Deployment
metadata:
  name: llms-service
  labels:
    app: llms-service
    repository: llms-service
    owner: JKOOUP
    tier: backend
    infrastructure: python
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llms-service
      tier: backend
      repository: llms-service
  template:
    metadata:
      labels:
        app: llms-service
        tier: backend
        owner: JKOOUP
        repository: llms-service
        infrastructure: python
    spec:
      nodeSelector:
        server-size: large
      containers:
        - name: llms-service
          image: cr.yandex/crpqcg70aaep5tihmd33/llms-service:latest
          env:
            - name: KAFKA_BROKER_ADDR
              value: "{{KAFKA_BROKER_ADDR}}"
            - name: KAFKA_BROKER_PORT
              value: "9092"
            - name: KAFKA_REQUEST_TOPIC
              value: "llm_tests_launch_tasks"
            - name: KAFKA_RESPONSE_TOPIC
              value: "llm_tests_results"
            - name: GIGACHAT_CREDENTIALS
              value: "{{GIGACHAT_CREDENTIALS}}"
            - name: GPT4_CREDENTIALS
              value: "{{GPT4_CREDENTIALS}}"
